# Generated by Django 4.0.5 on 2022-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplist', '0003_auto_20220421_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
