# Generated by Django 2.2.27 on 2022-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komarigotolist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('komarigoto', models.CharField(db_column='komarigoto', max_length=1000)),
            ],
        ),
    ]
