# Generated by Django 2.2.27 on 2022-05-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid02', '0002_eikyo1_eikyo2_genin1_genin2'),
    ]

    operations = [
        migrations.AddField(
            model_name='komarigotolist',
            name='eikyo1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vid02.Eikyo1'),
        ),
        migrations.AddField(
            model_name='komarigotolist',
            name='eikyo2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vid02.Eikyo2'),
        ),
        migrations.AddField(
            model_name='komarigotolist',
            name='genin1_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vid02.Genin1'),
        ),
        migrations.AddField(
            model_name='komarigotolist',
            name='genin2_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vid02.Genin2'),
        ),
    ]
