# Generated by Django 2.2.27 on 2022-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptxlist', '0006_alter_pptx_pptx_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptx',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
