# Generated by Django 2.2.27 on 2022-05-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pptxlist', '0008_pptx2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pptx2',
        ),
    ]
